### PR TITLE
Add REMOTE_PDB_QUIET=1 to allow silencing output

### LINKED ISSUE #17: Silent / quiet mode
cool tool!

I'm playing around with `curses` right now and a remote debugger is exceptionally good for this -- the one thing that's a bit unfortunate is `remote-pdb` will always print output breaking the curses output:

would you accept a PR which allows an option (and environment variable) to silence this?

### PR DESCRIPTION
**Pull request by asottile**
Resolves #17

### CODE REVIEW

**Comment by asottile** [comment]
I couldn't figure out a good way to test this, I'll add the changelog after that and/or after my other PR merges (since it will inevitably conflict) 👍

**Comment by ionelmc** [comment]
Oooof ... it's the port finding problem. I'll write that test don't worry.

**Comment by ionelmc** [comment]
I pushed the tests, lets see what happens on CI

**Comment by asottile** [comment]
`pip` needs an upgrade on appveyor it seems

**Pull request merged**
